<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-02-05">

<title>Amazon Certifications: the lies we spotted and the innovation we appreciated – Giorgia Santucci</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Giorgia Santucci</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/giorgia-santucci/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Amazon Certifications: the lies we spotted and the innovation we appreciated</h1>
            <p class="subtitle lead">Communicating sustainability features in the beauty market</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">February 5, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="amazon-certification-program-and-climate-pledge" class="level2">
<h2 class="anchored" data-anchor-id="amazon-certification-program-and-climate-pledge">Amazon Certification program and Climate Pledge</h2>
<p>Despite the presence of highly specialized beauty e-commerce platforms, <a href="https://ecommercedb.com/ranking/stores/it/personal-care">Amazon is still the major e-commerce platform for cosmetics in Italy</a>. The dedicated category on its website, <strong>“Beauty”</strong>:</p>
<ol type="1">
<li>Holds almost <em>7% of the share of total sales</em> from the entire website</li>
<li>Is the platform’s <em>2nd fastest-growing product category</em></li>
<li>Is <strong><em>the most profitable category for sellers</em></strong> (according to <em>Edge by Ascential Retail Insight &amp; Market Share, 2022</em>)</li>
</ol>
<p>Amazon has an advantageous market position over other digital beauty retailers not only thanks to the large and diverse cosmetics selection, but also because the <strong>User Experience is highly optimized</strong>. This is what we’ll be talking about in this article, more specifically about one of those features that, in my opinion, makes Amazon UI unique and extremly user-friendly. The <strong>Amazon Climate Pledge Certification Program</strong>.</p>
</section>
<section id="amazon-ui-ux-the-innovation-i-appreciated" class="level2">
<h2 class="anchored" data-anchor-id="amazon-ui-ux-the-innovation-i-appreciated">Amazon UI &amp; UX, the innovation I appreciated</h2>
<p>As consumers express a need, the market responds. Nowadays, as many times we pointed it out, consumers are more environmentally conscious and seek for products with certain features to satisfy their non-egoistic needs: <em>cruelty-free, organic, ethical, vegan, vegetarian, non-GMO, etc…</em><br>
But once the products get into the market, <strong>how do we make sure that all the feautures that make the product unique, are well highlighted and communicated to the consumers?</strong></p>
<p>Here’s where I think Amazon makes a difference. While other digital retailers are struggling to organize their products and their feautures, using search filters and random anonimous labels, Amazon opted for a more structured approach to help customers distinguish products with sustainability features.</p>
<p>Within the <em>Climate Pledge Friendly initiative</em>, <strong>Amazon has partnered with a wide range of external certifications</strong>, including those from government agencies, non-profit organizations and independent laboratories to label their products with the most relevant sustainability features.</p>
<p>Climate Pledge Friendly helps customers identify products that have obtained sustainability certifications easily and intuitively: <strong>shoppers can filter by the Climate Pledge Friendly badge</strong> to quickly find all products with sustainability certifications, or when shopping by category they can easily recognize the <strong>certified products thanks to the “leaf-shaped”logo</strong>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="amazon_files/figure-html/cell-2-1-amazUI.jpg" class="img-fluid figure-img"></p>
<figcaption>Amazon User Interface while exploring Climate Pledge Friendly products</figcaption>
</figure>
</div>
<p>This innovative UI design makes User Experience so much easier. Products features are clearly and smartly displayed. The certifications that go with the products <strong>overcome the lack of confidence</strong> that customers may face when shopping for products with sustainability features. <a href="https://giorgia-santucci.github.io/posts/Analysis%20of%20Popularity%20and%20Sentiment%20of%20Cruelty-free%20declared%20and%20certified%20cosmetics/main.html">Groundless claims</a> are just a distant memory! Certifications details are intuitively and quickly accessible, making products qualities easier to understand and <strong>products more attractive</strong>.</p>
<p>Amazon User Interface is the only one among italian e-commerce beauty platforms, at the time of this research, that provides customers with such a <strong>User Experience that eliminates ambiguity and lack of evidence about sustainability claims on products</strong>, taking the mission of communicating sustainability features to the next level.</p>
</section>
<section id="who-are-the-sustainable-brands-behind-climate-pledge-certifications" class="level2">
<h2 class="anchored" data-anchor-id="who-are-the-sustainable-brands-behind-climate-pledge-certifications">Who are the sustainable brands behind Climate Pledge Certifications?</h2>
<p>Collecting data from Amazon Beauty I identified <strong>17 different certifications</strong>. We’ll not see them all, but only the ones that are most popular and abundant in terms of amount of products. Let’s rather see who are the sustainable brands behind these certifications</p>
<section id="associazione-italiana-agricoltura-biologica-aiab" class="level3">
<h3 class="anchored" data-anchor-id="associazione-italiana-agricoltura-biologica-aiab">Associazione Italiana Agricoltura Biologica (AIAB)</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="amazon_files/figure-html/cell-3-1-aiba.png" class="img-fluid figure-img"></p>
<figcaption>Top 10 Brands with AIAB certification</figcaption>
</figure>
</div>
<p>AIAB certification has a double significance: it certifies <strong>only products manufactured by italian companies</strong> and it <em>“guarantees compliance with production specification and the application of best practices such as <strong>non-allergenic and non-irritating vegetable based raw materials</strong> and <strong>agricultural and livestock products from organic farming”</strong></em> on cosmetic products. This certification was the first ever recognition on organic cosmetics in Italy, established over 10 years ago, and focuses on both location where the manufacturing takes place and the raw materials used. 4% of products in the sample have this certification (271 products).</p>
</section>
<section id="compact-by-design-amazon-certification" class="level3">
<h3 class="anchored" data-anchor-id="compact-by-design-amazon-certification">Compact by Design (Amazon Certification)</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="amazon_files/figure-html/cell-3-2-cbyd.png" class="img-fluid figure-img"></p>
<figcaption>Top 10 Brands with Compact by Design certification</figcaption>
</figure>
</div>
<p>Because this certification is awarded by Amazon, you may think it only has to do with Amazon’s packaging and shipping practices but it’s not only about that. Amazon applies <em>Compact by Design</em> to products that have an <strong>“efficient design that is optimized for size and space”</strong>. This means that only products whose packaging is designed to be as small and lightweight as possible will be awarded this certification. But, how does Amazon identify products that are <em>compact</em>? In order to identify products that are compact, Amazon uses an <strong>indicator</strong> called <strong>“Unit Efficiency”</strong>: this value is calculated for an entire category and used as a <em>limit value</em> to determine if a product is compact or not. The brands displayed in the pie chart above are the Top 10 brands with the highest amount of products with this certification. Compact by Design products are 17% of the sample (1103 products).</p>
</section>
<section id="cradle-to-cradle" class="level3">
<h3 class="anchored" data-anchor-id="cradle-to-cradle">Cradle to Cradle</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="amazon_files/figure-html/cell-3-3-cradle.png" class="img-fluid figure-img"></p>
<figcaption>Top 10 Brands with Cradle to Cradle certification</figcaption>
</figure>
</div>
<p>This certification program <strong>evaluates both the product itself and its packaging</strong>, depending on the scope defined by the manufacturer. The certification assesses the entire lifecycle of the product, including its ingredients, materials, and packaging, to ensure they meet the program’s <strong>standards for sustainability and circularity</strong>. Products certified with this label are expected to be formulated with a <strong>chemical composition that includes only non-toxic, biodegradable, or recyclable materials</strong>. Plus, product packaging materials must be designed for reuse, recycling, or composting; so the use of renewable, recyclable, or biodegradable materials is encouraged. C2C certified products in the Beauty category are only 109, and occupy 1.7% of the sample.</p>
<section id="the-following-two-certifications-are-issued-by-amazon-and-do-not-regard-sustainability-but-they-still-reward-some-important-aspects-of-products-and-may-be-a-feature-to-keep-an-eye-on-for-consumers" class="level4">
<h4 class="anchored" data-anchor-id="the-following-two-certifications-are-issued-by-amazon-and-do-not-regard-sustainability-but-they-still-reward-some-important-aspects-of-products-and-may-be-a-feature-to-keep-an-eye-on-for-consumers">The following two certifications are issued by Amazon and do not regard sustainability, but they still reward some important aspects of products and may be a feature to keep an eye on, for consumers</h4>
</section>
</section>
<section id="piccola-azienda-the-lies-of-small-businesses" class="level3">
<h3 class="anchored" data-anchor-id="piccola-azienda-the-lies-of-small-businesses">Piccola Azienda, the lies of “small businesses”</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="amazon_files/figure-html/cell-3-5-piccolazienda.png" class="img-fluid figure-img"></p>
<figcaption>Top 10 Brands with Piccola Azienda certification</figcaption>
</figure>
</div>
<p>Displayed above we see the Top 10 Small Business with the highest amount of products. <strong>Amazon defines “Small Business”</strong> as <em>“artisanal businesses that are part of Amazon Handmade or brand owners registered in the Amazon Brand Registry, based in Italy, which <strong>employ fewer than 250 employees</strong> and have an annual <strong>turnover not exceeding 50 million euros</strong>, and/or an <strong>annual total balance sheet not exceeding 43 million euros”</strong></em>. There are two things I would like to be noticed:</p>
<ol type="1">
<li><p>Let’s immediately point out that <strong>Amazon definition for “Small Business” is actually the definition for medium-sized companies</strong> (adopted by the Italian Government and supported by the European Commission).</p></li>
<li><p>Look at the brands in the pie chart…do they sound “small businesses” to you? I mean, Gyada, Alama, Divina blk, phitofilos ecc. are clearly small business under all points of view. They are small and indipendent brands that serve a niche market with (at most) a European reach, they’re specialized in organic, natural and premium beauty products. BUT, SOMATOLINE, BAREX…SMALL AND ARTISANAL?</p></li>
</ol>
<p>Just to be clear,</p>
<p><strong>Somatoline is owned by L’Oréal Group</strong>, one of the largest cosmetics companies globally. As a brand under a major multinational corporation, Somatoline benefits from the parent company’s extensive resources, distribution networks, and market reach. I can’t mention the exact Somatoline’s or L’Oréal’s annual turnover, but given the facts above, I am quite sure it far exceeds the €50 million threshold for Small or Medium Businesses. There should be no need to argue wether Somatoline is an artisanal business or not, obviously it is not.</p>
<p><strong>Barex is a business unit of INEOS</strong>, a large multinational chemical company. It operates in the pharmaceutical market and it’s present in Europe, North America, and Asia. Barex association with INEOS suggests it is part of a larger corporate structure with significant resources and market influence. So, very very unlikely that Barex can be considered a small business that produces artisanal products.</p>
<p><em>Be careful dear Amazon, because I have just spotted not one but two attempts to mislead consumers with your claims: first the “small business” terminology adapted to your convenience, and then the inclusion of two big brands under the “Piccola Azienda” claim</em></p>
</section>
<section id="made-in-italy" class="level3">
<h3 class="anchored" data-anchor-id="made-in-italy">Made in Italy</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="amazon_files/figure-html/cell-3-4-madeinita.png" class="img-fluid figure-img"></p>
<figcaption>Top 10 Brands with Made in Italy certification</figcaption>
</figure>
</div>
<p>The Amazon Certification “Made in Italy” awards <em>“products which have been manufactured or have undergone their last substantial processing in Italy”</em>. This is the most numerous certification in the Beauty category, with <strong>2929 products</strong>. On the entire sample of Beauty products, 46% of them have this certification and those you see displayed in the pie chart above are the brands with the highest amount of products under this label. As an italian, I feel very proud of seeing some of the beauty leading brands of the entire market labeled with our flag. Made in Italy is such a <strong>strong example of Nation Branding</strong>: synonymous of quality, craftsmanship and luxury when applied to the Beauty industry.</p>
</section>
</section>
<section id="which-climate-pledge-certification-is-more-popular-among-consumers" class="level2">
<h2 class="anchored" data-anchor-id="which-climate-pledge-certification-is-more-popular-among-consumers">Which Climate Pledge Certification is more popular among consumers?</h2>
<p>To understand which certification among the ones from Amazon Climate Pledge initiave is more popular among consumers, I run a linear regression analysis on Amazon beauty product data, collected from Amazon.it during summer 2024. Thanks to web-scraping techniques I was able to collect 28109 observations at first, but after pre-processing and cleaning <em>only</em> 9652 observations were used for the analysis. The data was collected from Amazon Beauty, more specifically from body care, face care and hair care categories.</p>
<p>In the regression model, I included the following variables:</p>
<p><span class="math display">\[𝑃𝑜𝑝𝑢𝑙𝑎𝑟𝑖𝑡𝑦 = 𝛼 + 𝛽1Certification\]</span></p>
<p>where <em>Popularity</em> is given by the number of reviews per product, <em>𝛼 is a constant</em> that represent the average number of reviews of products without any certification, and <em>𝛽1 Certification</em> is one-hot encoded dummy variable. I run the model to <strong>understand how this certifications are related to the popularity of the products</strong>, and I have displayed here only the significant coefficients</p>
<div id="tbl-letters" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-letters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Results
</figcaption>
<div aria-describedby="tbl-letters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Cert</th>
<th>Coef.</th>
<th>St.Err</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>𝛼</td>
<td>578</td>
<td>19.0</td>
</tr>
<tr class="even">
<td>AIAB</td>
<td>330.9**</td>
<td>181.9</td>
</tr>
<tr class="odd">
<td>Compact by Design</td>
<td>224***</td>
<td>89.8</td>
</tr>
<tr class="even">
<td>Cradle to Cradle</td>
<td>3134***</td>
<td>280.6</td>
</tr>
<tr class="odd">
<td>Made in Italy</td>
<td>-224***</td>
<td>61.3</td>
</tr>
<tr class="even">
<td>Piccola Azienda</td>
<td>-398.2***</td>
<td>78.8</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>***p&lt;0.01, **p&lt;0.05, *p&lt;0.1</p>
<p>As you can see, 𝛼 takes a value of 578 meaning that, on average, <strong>a product without any certification has 578 reviews</strong>. Then we can compare our certifications with 𝛼 to understand how many reviews certified products totalize. Let’s start from <strong>the best perfoming ones</strong>:</p>
<ol type="1">
<li><p><strong>Cradle to Cradle</strong> certified products have an average of 3134 additional reviews compared to products without any certification. This means that products with Cradle to Cradle have 578 + 3134 = 3712 reviews.</p></li>
<li><p><strong>AIAB</strong> products have +330 additional reviews, for a total average of 908 reviews</p></li>
<li><p><strong>Compact by Design</strong> products have +224 additional reviews, for a total average of 802 reviews</p></li>
</ol>
<p>Now, our <strong>underperforming certifications</strong>:</p>
<ol start="4" type="1">
<li><p><strong>Made in Italy</strong> products have -224 reviews compared to products with no certification. Only 354 average reviews for our italian beauty products, I expected better results! And I can’t even find a reason for this, since the Top 10 brands representing this category are well-known and appreciated nationally</p></li>
<li><p><strong>Piccola Azienda</strong> products have -398.2 reviews compared to products with no certification. If the certification was actually rewarding the real Piccole Aziende Italiane, I would have accepted the outcome and said that it’s normal. Small businesses are not supposed to be popular or they wouldn’t be small. But in this case, with Somatoline and Barex playing the game…I don’t know how to interpret this result</p></li>
</ol>
</section>
<section id="conclusion-the-lies-we-spotted-and-the-innovations-we-appreciated" class="level2">
<h2 class="anchored" data-anchor-id="conclusion-the-lies-we-spotted-and-the-innovations-we-appreciated">Conclusion: the lies we spotted and the innovations we appreciated</h2>
<p>Amazon, could you ever be more controversial than this? In this article, I tought I would have just congratulated with you for having the most innovative, organized, user-friendly User Interface, but I have spotted some lies on the way…</p>
<p>In this article we have seen how Amazon is using certifications to promote sustainable products. I compliment with Amazon for being the first e-commerce to improve UI &amp; UX so that consumers can easily identify products with sustainable features. Certainly, this User Interface should be used as an example for other platforms, and the concept of combining a credible certification to each product attribute should always be implemented.</p>
<p>I appreciate the labels for “Piccola Azienda” and “Made in Italy”: these are interesting features for many customers and represent a great opportunities for the real small businesses, that can exploit Amazon customer reach as on the fast lane. Furthermore, I believe displaying this certifications also improves Amazon image and reputation, which may suffer of lack of credibility and autenticity.</p>
<p>Anyway, some improvements are absolutelly needed in order to develop the idea correctly and fairly. The criteria for the classification of “Small Business” need to be revised. <strong>If Amazon wants to display </strong><em>Piccole Aziende</em><strong>, the criteria for the number of employees, the annual turnover and the balance sheet must be adjusted</strong>. While, if Amazon wants to maintain his current partners for this certification, the name of the certification must be changed to something else. I would suggest <em>“Rising Boutique Brands”</em>, to highlight the craftsmanship and refinement of the products.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>